"""autogenerated at startup.

Revision ID: ad74f2a76227
Revises:
Create Date: 2025-10-13 19:55:27.466880
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad74f2a76227"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade the revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_issuer",
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("token_issuer_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_token_issuer_created_by"), "token_issuer", ["created_by"], unique=False)
    op.create_index(op.f("ix_token_issuer_id"), "token_issuer", ["id"], unique=False)
    op.create_index(op.f("ix_token_issuer_name"), "token_issuer", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_issuer_name"), table_name="token_issuer")
    op.drop_index(op.f("ix_token_issuer_id"), table_name="token_issuer")
    op.drop_index(op.f("ix_token_issuer_created_by"), table_name="token_issuer")
    op.drop_table("token_issuer")
    # ### end Alembic commands ###
